/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import '@stencil/state-tunnel';
import '@stencil/router';


declare global {

  namespace StencilComponents {
    interface AppBurger {
      'toggleLeftSidebar': () => void;
    }
  }

  interface HTMLAppBurgerElement extends StencilComponents.AppBurger, HTMLStencilElement {}

  var HTMLAppBurgerElement: {
    prototype: HTMLAppBurgerElement;
    new (): HTMLAppBurgerElement;
  };
  interface HTMLElementTagNameMap {
    'app-burger': HTMLAppBurgerElement;
  }
  interface ElementTagNameMap {
    'app-burger': HTMLAppBurgerElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-burger': JSXElements.AppBurgerAttributes;
    }
  }
  namespace JSXElements {
    export interface AppBurgerAttributes extends HTMLAttributes {
      'toggleLeftSidebar'?: () => void;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppIcon {
      'name': string;
    }
  }

  interface HTMLAppIconElement extends StencilComponents.AppIcon, HTMLStencilElement {}

  var HTMLAppIconElement: {
    prototype: HTMLAppIconElement;
    new (): HTMLAppIconElement;
  };
  interface HTMLElementTagNameMap {
    'app-icon': HTMLAppIconElement;
  }
  interface ElementTagNameMap {
    'app-icon': HTMLAppIconElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-icon': JSXElements.AppIconAttributes;
    }
  }
  namespace JSXElements {
    export interface AppIconAttributes extends HTMLAttributes {
      'name'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppMarked {
      'doc': string;
    }
  }

  interface HTMLAppMarkedElement extends StencilComponents.AppMarked, HTMLStencilElement {}

  var HTMLAppMarkedElement: {
    prototype: HTMLAppMarkedElement;
    new (): HTMLAppMarkedElement;
  };
  interface HTMLElementTagNameMap {
    'app-marked': HTMLAppMarkedElement;
  }
  interface ElementTagNameMap {
    'app-marked': HTMLAppMarkedElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-marked': JSXElements.AppMarkedAttributes;
    }
  }
  namespace JSXElements {
    export interface AppMarkedAttributes extends HTMLAttributes {
      'doc'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface DemoCard {
      'demoUrl': string;
      'description': string;
      'imgPath': string;
      'name': string;
      'sourceUrl': string;
    }
  }

  interface HTMLDemoCardElement extends StencilComponents.DemoCard, HTMLStencilElement {}

  var HTMLDemoCardElement: {
    prototype: HTMLDemoCardElement;
    new (): HTMLDemoCardElement;
  };
  interface HTMLElementTagNameMap {
    'demo-card': HTMLDemoCardElement;
  }
  interface ElementTagNameMap {
    'demo-card': HTMLDemoCardElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'demo-card': JSXElements.DemoCardAttributes;
    }
  }
  namespace JSXElements {
    export interface DemoCardAttributes extends HTMLAttributes {
      'demoUrl'?: string;
      'description'?: string;
      'imgPath'?: string;
      'name'?: string;
      'sourceUrl'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface DemoPage {

    }
  }

  interface HTMLDemoPageElement extends StencilComponents.DemoPage, HTMLStencilElement {}

  var HTMLDemoPageElement: {
    prototype: HTMLDemoPageElement;
    new (): HTMLDemoPageElement;
  };
  interface HTMLElementTagNameMap {
    'demo-page': HTMLDemoPageElement;
  }
  interface ElementTagNameMap {
    'demo-page': HTMLDemoPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'demo-page': JSXElements.DemoPageAttributes;
    }
  }
  namespace JSXElements {
    export interface DemoPageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface DocumentComponent {
      'pages': string[];
    }
  }

  interface HTMLDocumentComponentElement extends StencilComponents.DocumentComponent, HTMLStencilElement {}

  var HTMLDocumentComponentElement: {
    prototype: HTMLDocumentComponentElement;
    new (): HTMLDocumentComponentElement;
  };
  interface HTMLElementTagNameMap {
    'document-component': HTMLDocumentComponentElement;
  }
  interface ElementTagNameMap {
    'document-component': HTMLDocumentComponentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'document-component': JSXElements.DocumentComponentAttributes;
    }
  }
  namespace JSXElements {
    export interface DocumentComponentAttributes extends HTMLAttributes {
      'pages'?: string[];
    }
  }
}


declare global {

  namespace StencilComponents {
    interface LandingPage {

    }
  }

  interface HTMLLandingPageElement extends StencilComponents.LandingPage, HTMLStencilElement {}

  var HTMLLandingPageElement: {
    prototype: HTMLLandingPageElement;
    new (): HTMLLandingPageElement;
  };
  interface HTMLElementTagNameMap {
    'landing-page': HTMLLandingPageElement;
  }
  interface ElementTagNameMap {
    'landing-page': HTMLLandingPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'landing-page': JSXElements.LandingPageAttributes;
    }
  }
  namespace JSXElements {
    export interface LandingPageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface LazyIframe {
      'frameBorder': string;
      'height': string;
      'name': string;
      'scrolling': string;
      'src': string;
      'width': string;
    }
  }

  interface HTMLLazyIframeElement extends StencilComponents.LazyIframe, HTMLStencilElement {}

  var HTMLLazyIframeElement: {
    prototype: HTMLLazyIframeElement;
    new (): HTMLLazyIframeElement;
  };
  interface HTMLElementTagNameMap {
    'lazy-iframe': HTMLLazyIframeElement;
  }
  interface ElementTagNameMap {
    'lazy-iframe': HTMLLazyIframeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'lazy-iframe': JSXElements.LazyIframeAttributes;
    }
  }
  namespace JSXElements {
    export interface LazyIframeAttributes extends HTMLAttributes {
      'frameBorder'?: string;
      'height'?: string;
      'name'?: string;
      'scrolling'?: string;
      'src'?: string;
      'width'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface NotfoundPage {

    }
  }

  interface HTMLNotfoundPageElement extends StencilComponents.NotfoundPage, HTMLStencilElement {}

  var HTMLNotfoundPageElement: {
    prototype: HTMLNotfoundPageElement;
    new (): HTMLNotfoundPageElement;
  };
  interface HTMLElementTagNameMap {
    'notfound-page': HTMLNotfoundPageElement;
  }
  interface ElementTagNameMap {
    'notfound-page': HTMLNotfoundPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'notfound-page': JSXElements.NotfoundPageAttributes;
    }
  }
  namespace JSXElements {
    export interface NotfoundPageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ProductPage {

    }
  }

  interface HTMLProductPageElement extends StencilComponents.ProductPage, HTMLStencilElement {}

  var HTMLProductPageElement: {
    prototype: HTMLProductPageElement;
    new (): HTMLProductPageElement;
  };
  interface HTMLElementTagNameMap {
    'product-page': HTMLProductPageElement;
  }
  interface ElementTagNameMap {
    'product-page': HTMLProductPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'product-page': JSXElements.ProductPageAttributes;
    }
  }
  namespace JSXElements {
    export interface ProductPageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface PwaPage {

    }
  }

  interface HTMLPwaPageElement extends StencilComponents.PwaPage, HTMLStencilElement {}

  var HTMLPwaPageElement: {
    prototype: HTMLPwaPageElement;
    new (): HTMLPwaPageElement;
  };
  interface HTMLElementTagNameMap {
    'pwa-page': HTMLPwaPageElement;
  }
  interface ElementTagNameMap {
    'pwa-page': HTMLPwaPageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'pwa-page': JSXElements.PwaPageAttributes;
    }
  }
  namespace JSXElements {
    export interface PwaPageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ResourcePage {

    }
  }

  interface HTMLResourcePageElement extends StencilComponents.ResourcePage, HTMLStencilElement {}

  var HTMLResourcePageElement: {
    prototype: HTMLResourcePageElement;
    new (): HTMLResourcePageElement;
  };
  interface HTMLElementTagNameMap {
    'resource-page': HTMLResourcePageElement;
  }
  interface ElementTagNameMap {
    'resource-page': HTMLResourcePageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'resource-page': JSXElements.ResourcePageAttributes;
    }
  }
  namespace JSXElements {
    export interface ResourcePageAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface SiteHeader {

    }
  }

  interface HTMLSiteHeaderElement extends StencilComponents.SiteHeader, HTMLStencilElement {}

  var HTMLSiteHeaderElement: {
    prototype: HTMLSiteHeaderElement;
    new (): HTMLSiteHeaderElement;
  };
  interface HTMLElementTagNameMap {
    'site-header': HTMLSiteHeaderElement;
  }
  interface ElementTagNameMap {
    'site-header': HTMLSiteHeaderElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'site-header': JSXElements.SiteHeaderAttributes;
    }
  }
  namespace JSXElements {
    export interface SiteHeaderAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface SiteMenu {

    }
  }

  interface HTMLSiteMenuElement extends StencilComponents.SiteMenu, HTMLStencilElement {}

  var HTMLSiteMenuElement: {
    prototype: HTMLSiteMenuElement;
    new (): HTMLSiteMenuElement;
  };
  interface HTMLElementTagNameMap {
    'site-menu': HTMLSiteMenuElement;
  }
  interface ElementTagNameMap {
    'site-menu': HTMLSiteMenuElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'site-menu': JSXElements.SiteMenuAttributes;
    }
  }
  namespace JSXElements {
    export interface SiteMenuAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface StencilSite {

    }
  }

  interface HTMLStencilSiteElement extends StencilComponents.StencilSite, HTMLStencilElement {}

  var HTMLStencilSiteElement: {
    prototype: HTMLStencilSiteElement;
    new (): HTMLStencilSiteElement;
  };
  interface HTMLElementTagNameMap {
    'stencil-site': HTMLStencilSiteElement;
  }
  interface ElementTagNameMap {
    'stencil-site': HTMLStencilSiteElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'stencil-site': JSXElements.StencilSiteAttributes;
    }
  }
  namespace JSXElements {
    export interface StencilSiteAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
